//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovTours
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCopy
    {
        public int ClientID { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientLastName { get; set; }
        public string ClientPatronymic { get; set; }
        public string ClientPassData { get; set; }
        public System.DateTime ClientBirthday { get; set; }
        public string ClientCity { get; set; }
        public string ClientAddress { get; set; }
        public string ClientPhone { get; set; }
    }
}
