//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovTours
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pension
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pension()
        {
            this.TravelPack = new HashSet<TravelPack>();
        }
    
        public int PensionID { get; set; }
        public string PensionName { get; set; }
        public string PensionCountry { get; set; }
        public string PensionCity { get; set; }
        public string PensionAddress { get; set; }
        public string PensionPhone { get; set; }
        public string PensionTerritoryDiscription { get; set; }
        public Nullable<int> PensionRoomCount { get; set; }
        public bool PensionPool { get; set; }
        public string PensionMedService { get; set; }
        public bool PensionSpa { get; set; }
        public string PensionLvl { get; set; }
        public Nullable<double> PensionSeaDistanceKm { get; set; }
        public int HousingID { get; set; }
    
        public virtual Housing Housing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelPack> TravelPack { get; set; }
    }
}
