//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovTours
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelAgencyEntities : DbContext
    {
        private static TravelAgencyEntities _context;

        public static TravelAgencyEntities GetContext()
        {
            if (_context == null)
                _context = new TravelAgencyEntities();
            return _context;
        }
        public TravelAgencyEntities()
            : base("name=TravelAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientCopy> ClientCopy { get; set; }
        public virtual DbSet<Housing> Housing { get; set; }
        public virtual DbSet<HousingType> HousingType { get; set; }
        public virtual DbSet<Pension> Pension { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<TourSell> TourSell { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
        public virtual DbSet<TravelPack> TravelPack { get; set; }
    }
}
