//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovTours
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.TourSell = new HashSet<TourSell>();
        }
    
        public int TourID { get; set; }
        public string TourName { get; set; }
        public string TourEatType { get; set; }
        public decimal TourDayPrice { get; set; }
        public string TourCity { get; set; }
        public string TourPhoto { get; set; }
        public int HousingTypeID { get; set; }
        public int TransportID { get; set; }
    
        public virtual HousingType HousingType { get; set; }
        public virtual Transport Transport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourSell> TourSell { get; set; }

        public string TourTransportType
        {
            get
            {
                return Transport.TransportName;
            }
        }

        public string TourHousingType
        {
            get
            {
                return HousingType.HousingTypeName;
            }
        }
    }
}
