//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafikovTours
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourSell
    {
        public int TourSellID { get; set; }
        public int ClientID { get; set; }
        public int TourID { get; set; }
        public Nullable<decimal> TourSellPrice { get; set; }
        public int TourSellDurationDay { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
